import { useState } from "react";
import { useSearchParams } from "react-router-dom";
import { ArrowRight, Search } from "lucide-react";
import { useCareResource } from "../hooks/useCareResource";
import { Banner, Button, Card, EmptyState, Field, LoadingState } from "../components/ui";
import DoctorSummary from "../components/appointments/DoctorSummary";
import { feeText } from "../utils/appointments";
export default function Doctors() {
  const [params] = useSearchParams(), [search, setSearch] = useState(params.get("specialty") || ""), [submitted, setSubmitted] = useState(search), [sort, setSort] = useState("recommended"), [page, setPage] = useState(1);
  const query = new URLSearchParams({ search: submitted, sort, page, limit: 12 }), resource = useCareResource("/doctor?" + query);
  const doctors = Array.isArray(resource.data) ? resource.data : resource.data?.items || [];
  return <main className="mp-page"><div className="mp-section-heading"><div><p className="mp-eyebrow">Find your next step in care</p><h1>Connect Doctor</h1><p>Explore independent care and hospital doctors. Choose a profile to see the right booking context.</p></div><Button to="/my-appointments" variant="secondary">My appointments</Button></div><Card as="form" onSubmit={event => { event.preventDefault(); setSubmitted(search); setPage(1); }}><div className="mp-discovery-filters"><Field label="Search doctors" placeholder="Name, specialty or clinic" value={search} onChange={event => setSearch(event.target.value)} /><Field as="select" label="Sort doctors" value={sort} onChange={event => { setSort(event.target.value); setPage(1); }}><option value="recommended">Recommended</option><option value="rating">Rating</option><option value="experience">Experience</option></Field><Button type="submit"><Search size={17} />Search</Button></div></Card>
    {resource.error && <Banner action={<Button onClick={resource.refresh}>Retry search</Button>}>{resource.error}</Banner>}{resource.loading && !resource.data ? <LoadingState>Loading doctor profiles...</LoadingState> : !doctors.length && !resource.error ? <Card><EmptyState title="No doctors match this search.">Try a different name or specialty.</EmptyState></Card> : <div className="mp-doctor-grid">{doctors.map(doctor => <Card key={doctor._id}><DoctorSummary doctor={doctor} compact /><div className="mp-fee-row"><span>Listed consultation fee</span><strong>{feeText(Number.isFinite(Number(doctor.consultationFee)) ? { amountMinor: Math.round(Number(doctor.consultationFee) * 100), currency: "INR" } : null)}</strong></div>{doctor.hospitalContext ? <><p className="mp-field-hint">{doctor.hospitalContext.hospitalName} · {doctor.hospitalContext.departmentName}</p><Button to={"/hospitals/" + doctor.hospitalContext.hospitalSlug + "?doctor=" + doctor._id}>Hospital availability <ArrowRight size={16} /></Button></> : <div className="mp-actions"><Button to={"/appointment/book/" + doctor._id}>See availability <ArrowRight size={16} /></Button><Button to={"/doctorsProfile/" + doctor._id} variant="secondary">View profile</Button></div>}</Card>)}</div>}
    <nav className="mp-actions" aria-label="Doctor result pages"><Button variant="secondary" disabled={page <= 1 || resource.loading} onClick={() => setPage(value => value - 1)}>Previous</Button><span>Page {page}{resource.data?.totalPages ? " of " + resource.data.totalPages : ""}</span><Button variant="secondary" disabled={resource.loading || page >= (resource.data?.totalPages || 1)} onClick={() => setPage(value => value + 1)}>Next</Button></nav>
  </main>;
}
