import { useState } from "react";
import { useNavigate } from "react-router-dom";
import axios from "axios";
import { Banner, Button, Card, Field } from "../components/ui";
import { AccountPage, Feedback, PasswordField } from "../components/account/AccountUI";
import useFormTask from "../hooks/useFormTask";
import { BACKEND_URL } from "../utils";
const types = [["private", "Private Hospital"], ["government", "Government Hospital"], ["clinic", "Clinic"], ["diagnostic-center", "Diagnostic Center"], ["nursing-home", "Nursing Home"]];
const systems = [["allopathic", "Allopathic / Modern Medicine"], ["ayurveda", "Ayurveda"], ["homeopathy", "Homeopathy"], ["yoga_wellness", "Yoga & Wellness"], ["integrative", "Integrative Care"]];
export default function HospitalAdminSignup() {
  const [form, setForm] = useState({ name: "", email: "", phone: "", type: "private", medicineSystem: "allopathic", registrationNumber: "", adminName: "", adminPassword: "", line1: "", city: "", state: "", pincode: "" }), task = useFormTask(), navigate = useNavigate();
  const update = key => event => setForm(previous => ({ ...previous, [key]: event.target.value }));
  const field = (key, label, props = {}) => <Field key={key} label={label} value={form[key]} onChange={update(key)} disabled={task.busy} {...props} />;
  const submit = event => {
    event.preventDefault(); const { line1, city, state, pincode, ...details } = form;
    void task.run(signal => axios.post(`${BACKEND_URL}/api/hospitals/register`, { ...details, name: details.name.trim(), email: details.email.trim(), adminName: details.adminName.trim(), address: { line1, city, state, pincode } }, { signal }), response => {
      if (!response.data.hospital || !response.data.staff) throw new Error("Hospital registration response is incomplete.");
      sessionStorage.setItem("medipulse.hospitalAdmin", JSON.stringify({ hospital: response.data.hospital, staff: response.data.staff })); navigate("/hospital/admin", { replace: true });
    });
  };
  return <AccountPage wide title="Create Hospital Admin Portal" eyebrow="MediPulse for hospitals" description="Register your hospital and administrator account. Registration is submitted for verification."><Feedback feedback={task.feedback} />{!task.online && <Banner>You are offline. Your entries remain on this page until you reconnect.</Banner>}<Card as="form" onSubmit={submit} className="mp-stack" aria-busy={task.busy}><h2>Hospital details</h2>{field("name", "Hospital Name", { required: true, pattern: ".*[^ ].*" })}<div className="mp-form-row">{field("email", "Hospital Email", { required: true, type: "email", autoComplete: "email" })}{field("phone", "Phone", { type: "tel", pattern: "[1-9][0-9]{9}", hint: "Optional · 10 digits." })}</div>{field("registrationNumber", "Registration / License Number", { required: true, pattern: ".*[^ ].*" })}<div className="mp-form-row"><Field label="Hospital Type" as="select" value={form.type} disabled={task.busy} onChange={update("type")}>{types.map(([value, label]) => <option value={value} key={value}>{label}</option>)}</Field><Field label="Care System" as="select" value={form.medicineSystem} disabled={task.busy} onChange={update("medicineSystem")}>{systems.map(([value, label]) => <option value={value} key={value}>{label}</option>)}</Field></div><h2>Administrator and address</h2><div className="mp-form-row">{field("adminName", "Admin Name", { required: true, autoComplete: "name", pattern: ".*[^ ].*" })}<PasswordField label="Admin Password" required minLength={8} hint="At least 8 characters." autoComplete="new-password" value={form.adminPassword} disabled={task.busy} onChange={update("adminPassword")} /></div>{field("line1", "Address Line", { autoComplete: "address-line1" })}<div className="mp-form-row">{field("city", "City", { required: true, pattern: ".*[^ ].*", autoComplete: "address-level2" })}{field("state", "State", { required: true, pattern: ".*[^ ].*", autoComplete: "address-level1" })}</div>{field("pincode", "Pincode", { inputMode: "numeric", pattern: "[0-9]{6}", autoComplete: "postal-code", hint: "Optional · 6 digits." })}<p className="mp-field-hint">Verification status and trial details are available in your workspace after registration.</p><div className="mp-actions"><Button type="submit" disabled={task.busy || !task.online}>{task.busy ? "Creating workspace..." : "Create hospital workspace"}</Button><Button to="/hospital/login" disabled={task.busy} variant="secondary">Staff sign in</Button><Button to="/hospital" disabled={task.busy} variant="ghost">Back to hospital workspace</Button></div></Card></AccountPage>;
}
