import { useState } from "react";
import { useLocation } from "react-router-dom";
import { Download, RefreshCcw } from "lucide-react";
import { useAuth } from "../context/AuthContext";
import { useCareResource } from "../hooks/useCareResource";
import { Banner, Button, Card, EmptyState, Field, LoadingState, StatusBadge } from "../components/ui";
import { careLabels, doctorName, feeText, visitTime } from "../utils/appointments";
import LegacyVisitActions from "../components/appointments/LegacyVisitActions";
import { downloadAppointmentReceipt } from "../utils/appointmentReceipt";
export default function MyAppointments() {
  const { user, isAuth, role, loader } = useAuth(), location = useLocation(), owner = isAuth && role === "user" ? user?._id : null;
  const scheduled = useCareResource(owner ? "/api/scheduling/reservations?limit=50" : null, owner, 10000), history = useCareResource(owner ? "/appointment/history" : null, owner, 10000);
  const [filter, setFilter] = useState("all"), [message, setMessage] = useState("");
  const visits = scheduled.data?.visits || [], legacy = (history.data?.appointments || []).filter(item => !item.scheduleReservationId);
  const matches = status => filter === "all" || (filter === "upcoming" ? ["held", "confirmed", "queued", "active", "booking", "refund_pending"].includes(status) : status === filter);
  const refresh = () => { scheduled.refresh(); history.refresh(); };
  const download = async appointment => { try { await downloadAppointmentReceipt(appointment); } catch { setMessage("Unable to download the consultation summary. Try again."); } };
  if (loader) return <main className="mp-page"><LoadingState>Checking your patient session...</LoadingState></main>;
  if (!owner) return <main className="mp-page"><h1>My appointments</h1><EmptyState title="Your visits, in one place" action={<Button to={"/login?returnTo=" + encodeURIComponent(location.pathname)}>Patient sign in</Button>}>Sign in as a patient to follow appointments and consultation summaries.</EmptyState></main>;
  return <main className="mp-page mp-page--patient"><div className="mp-section-heading"><div><p className="mp-eyebrow">Care that stays connected</p><h1>My appointments</h1><p>Scheduled visits, current queues and consultation history.</p></div><Button variant="secondary" onClick={refresh}><RefreshCcw size={16} />Refresh visits</Button></div><div className="mp-form-row"><Field as="select" label="Show visits" value={filter} onChange={event => setFilter(event.target.value)}><option value="all">All visits</option><option value="upcoming">Upcoming / in progress</option><option value="completed">Completed</option><option value="cancelled">Cancelled</option></Field><Button to="/doctors">Find a doctor</Button></div>{message && <Banner>{message}</Banner>}{scheduled.error && <Banner action={<Button onClick={scheduled.refresh}>Retry scheduled visits</Button>}>{scheduled.error}</Banner>}{history.error && <Banner action={<Button onClick={history.refresh}>Retry history</Button>}>{history.error}</Banner>}
    {(scheduled.loading && !scheduled.data) || (history.loading && !history.data) ? <LoadingState>Loading your visits...</LoadingState> : !visits.length && !legacy.length && !scheduled.error && !history.error ? <Card><EmptyState title="No visits yet." action={<Button to="/doctors">Explore doctor availability</Button>}>Your confirmed bookings and current care queues will appear here.</EmptyState></Card> : !visits.some(item => matches(item.reservation.state)) && !legacy.some(item => matches(item.status)) ? <Card><EmptyState title="No visits match this filter." /></Card> : <div className="mp-visit-grid">{visits.filter(item => matches(item.reservation.state)).map(item => <Card key={item.reservation._id}><div className="mp-card-heading"><h2>{careLabels[item.session.appointmentType]}</h2><StatusBadge status={item.reservation.state === "confirmed" && item.appointment?.admissionState === "reserved" ? "reserved" : item.appointment?.status || item.reservation.state} /></div><p>{visitTime(item.reservation.startsAt, item.session.timezone)}</p><p className="mp-field-hint">{item.session.timezone} · {feeText(item.reservation.fee)} demo credits{item.reservation.familyMemberId ? " · Family visit" : ""}</p><p>{item.nextStep}</p><Button to={"/appointments/reservations/" + item.reservation._id}>Follow this visit</Button></Card>)}{legacy.filter(item => matches(item.status)).map(item => <Card key={item._id}><div className="mp-card-heading"><h2>Dr. {doctorName(item.doctor)}</h2><StatusBadge status={item.status} /></div><p>{item.visitMode === "in_person" ? "Hospital visit · in person" : "Current online queue"}</p><p className="mp-field-hint">{visitTime(item.createdAt, item.timezone)}{item.familyMemberId ? " · Family visit" : ""}</p>{["queued", "active"].includes(item.status) && item.visitMode !== "in_person" && <Button to={"/appointment/book/" + item.doctor?._id}>Open current visit</Button>}<LegacyVisitActions key={owner + ":" + item._id} appointment={item} owner={owner} onRefresh={history.refresh} />{item.receiptText && <Button variant="secondary" onClick={() => download(item)}><Download size={16} />Download draft summary</Button>}</Card>)}</div>}
    <p className="mp-field-hint" style={{ marginTop: 20 }}>Last refreshed {scheduled.refreshedAt?.toLocaleTimeString() || history.refreshedAt?.toLocaleTimeString() || "Not available"}. This view shows the 50 most recent scheduled reservations.</p>
  </main>;
}
