import { ArrowRight, Building2, Check, ClipboardList, HeartHandshake, MessageCircle, Stethoscope, Users } from "lucide-react";
import { Button, Card, EmptyState } from "../components/ui";

export function CompanyHome() {
  return <main className="mp-page"><section className="mp-hero" aria-labelledby="company-title"><div><p className="mp-eyebrow">For patients, doctors & hospital teams</p><h1 id="company-title">MediPulse</h1><p className="mp-hero-tagline">Care that stays connected.</p><p className="mp-lead">From finding an independent doctor to following a hospital visit, make the next step in care easier to understand.</p><div className="mp-actions"><Button href="/connect">Explore Connect <ArrowRight size={17} /></Button><Button href="#products" variant="secondary">For hospitals</Button></div></div><div className="mp-hero-panel" aria-label="Two services for connected care"><p className="mp-hero-panel-label">One platform. Two care journeys.</p><div className="mp-care-node"><span><Stethoscope size={25} /></span><div><h2>Independent care</h2><p>Doctors, online consultations and communities.</p></div></div><div className="mp-care-node"><span><Building2 size={25} /></span><div><h2>Hospital OPD</h2><p>Reservations, check-in and clinical queues.</p></div></div><div className="mp-hero-process"><span>Find care</span><ArrowRight size={14} /><span>Reserve a visit</span><ArrowRight size={14} /><span>Stay informed</span></div></div></section>
    <section id="products" aria-labelledby="products-title"><div className="mp-section-heading"><div><p className="mp-eyebrow">Choose your care journey</p><h2 id="products-title">Two services for connected care.</h2></div><p>Built around the people giving and receiving care.</p></div><div className="mp-product-grid"><Card className="mp-product-card"><span className="mp-product-icon"><HeartHandshake size={28} /></span><h2>MediPulse Connect</h2><p>A place for patients and independent doctors to meet, consult and stay connected.</p><ul><li><Check size={17} />Discover independent doctor profiles</li><li><Check size={17} />Join doctor-led patient communities</li><li><Check size={17} />Access online consultation queues</li></ul><div className="mp-actions"><Button href="/connect">Open Connect <ArrowRight size={16} /></Button></div></Card><Card className="mp-product-card"><span className="mp-product-icon"><Building2 size={28} /></span><h2>MediPulse for Hospitals</h2><p>A shared OPD workspace for staff, and a clearer visit journey for patients.</p><ul><li><Check size={17} />Manage reservations and physical check-in</li><li><Check size={17} />Coordinate department and doctor queues</li><li><Check size={17} />Give patients a branded hospital website</li></ul><div className="mp-actions"><Button href="/hospital">Open hospital workspace <ArrowRight size={16} /></Button><Button href="/hospitals" variant="ghost">Find a hospital</Button></div></Card></div></section><section className="mp-promise"><div><h2>Less uncertainty. A clearer next step.</h2><p>Find a doctor or hospital, choose the right care context, and follow your visit.</p></div><Button href="/hospitals" variant="secondary">Browse hospitals <ArrowRight size={16} /></Button></section>
  </main>;
}
export function ConnectHome() {
  return <main className="mp-page"><p className="mp-eyebrow">Independent care · your own doctor connection</p><h1 className="mp-title">MediPulse Connect</h1><p className="mp-lead">Care starts with a conversation. Find an independent doctor, join a community and access online consultations.</p><div className="mp-actions"><Button to="/doctors">Find independent doctors <ArrowRight size={17} /></Button><Button to="/communities" variant="secondary">Explore communities</Button></div><div className="mp-product-grid" style={{ marginTop: 40 }}><Card><div className="mp-card-heading"><h2>Your doctor, your care context</h2><Stethoscope size={23} /></div><p className="mp-lead">Browse profiles and start with a doctor&apos;s independent consultation queue.</p><Button to="/doctors" variant="ghost" style={{ marginTop: 18 }}>Browse doctors <ArrowRight size={16} /></Button></Card><Card><div className="mp-card-heading"><h2>Stay connected between visits</h2><MessageCircle size={23} /></div><p className="mp-lead">Discover patient communities and conversations led by doctors.</p><Button to="/communities" variant="ghost" style={{ marginTop: 18 }}>Find your community <Users size={17} /></Button></Card></div></main>;
}
export function StaffHome() {
  return <main className="mp-page"><div className="mp-hero"><div><p className="mp-eyebrow">MediPulse for Hospitals</p><h1 className="mp-title">Hospital workspace</h1><p className="mp-lead">One place for your team to coordinate the OPD journey. Sign in with the staff account issued by your hospital.</p><div className="mp-actions"><Button to="/hospital/login">Staff sign in <ArrowRight size={16} /></Button><Button to="/hospital/signup" variant="secondary">Register a hospital</Button></div></div><Card><div className="mp-card-heading"><h2>Care moves forward, together</h2><ClipboardList size={24} /></div><p className="mp-lead">Keep reservations separate from arrived patients, prepare vitals and coordinate the next consultation.</p><p className="mp-field-hint" style={{ marginTop: 20 }}>Your role and hospital determine the workspace you can access.</p></Card></div></main>;
}
export function RouteNotFound() { return <main className="mp-page"><EmptyState title="Page not found" action={<Button to="/">Return to this website</Button>}>This page is not available in this care workspace.</EmptyState></main>; }
