import { useEffect, useRef, useState } from "react";
import { useLocation, useParams, useSearchParams } from "react-router-dom";
import axios from "axios";
import { ArrowRight, CalendarPlus, Check, Clock3, HelpCircle, RefreshCcw } from "lucide-react";
import { useAuth } from "../context/AuthContext";
import { useProduct } from "../context/ProductContext";
import { useHospitalBrand } from "../components/ProductShell";
import { useCareResource, useOnlineStatus } from "../hooks/useCareResource";
import { Banner, Button, Card, Dialog, EmptyState, Field, LoadingState, StatusBadge } from "../components/ui";
import CallPanel from "../components/appointments/CallPanel";
import { bookingRequestKey, clearBookingRequest } from "../utils/bookingRequest";
import { BACKEND_URL } from "../utils";
import { calendarReminder, canCheckIn, careLabels, dateInZone, downloadText, feeText, timeOfDay, visitTime } from "../utils/appointments";

export default function ReservationTracking() {
  const { reservationId } = useParams(), { user, isAuth, role, loader } = useAuth(), product = useProduct(), { hospital } = useHospitalBrand(), online = useOnlineStatus(), location = useLocation();
  const owner = isAuth && role === "user" ? user?._id : null;
  const resource = useCareResource(owner ? "/api/scheduling/reservations/" + reservationId : null, owner, 10000);
  const visit = resource.data;
  const storage = `medipulse.visitAction.${owner}:${reservationId}`;
  const [intent, setIntent] = useState(() => { try { return JSON.parse(sessionStorage.getItem(storage)); } catch { return null; } });
  const currentScope = useRef(storage); currentScope.current = storage;
  useEffect(() => { try { setIntent(JSON.parse(sessionStorage.getItem(storage))); } catch { setIntent(null); } setDialog(null); setBusy(false); pending.current = false; }, [storage]);
  const [dialog, setDialog] = useState(null), [busy, setBusy] = useState(false), [message, setMessage] = useState(""), [clock, setClock] = useState(Date.now());
  const [date, setDate] = useState(dateInZone()), [target, setTarget] = useState(""), pending = useRef(false), alive = useRef(true);
  const [, setParams] = useSearchParams();
  useEffect(() => { alive.current = true; return () => { alive.current = false; }; }, [owner, reservationId]);
  useEffect(() => { const timer = setInterval(() => setClock(Date.now()), 10000); return () => clearInterval(timer); }, []);
  const clearIntent = () => { sessionStorage.removeItem(storage); setIntent(null); };
  useEffect(() => {
    if (!visit || !intent) return;
    const done = intent.kind === "cancel" ? visit.reservation.state === "cancelled" : intent.kind === "check-in" ? visit.appointment?.admissionState === "arrived" : visit.reservation.slotId === intent.body.slotId && visit.reservation.revision > intent.body.revision;
    if (done) { sessionStorage.removeItem(storage); setIntent(null); setDialog(null); setMessage("Your visit change is confirmed."); }
  }, [visit, intent, storage]);
  const query = visit ? new URLSearchParams({ doctorId: visit.session.doctorId, from: date, to: date, ...(visit.session.hospitalId ? { hospitalId: visit.session.hospitalId, departmentId: visit.session.departmentId } : {}) }) : null;
  const availability = useCareResource(dialog === "reschedule" && query ? "/api/scheduling/availability?" + query : null);
  const slots = (availability.data?.sessions || []).filter(item => item.appointmentType === visit?.session.appointmentType && item.fee.amountMinor === visit?.reservation.fee.amountMinor).flatMap(item => (item.slots || []).map(slot => ({ ...slot, session: item })));
  const change = async (kind, body = {}) => {
    if (pending.current || !owner || !online) return;
    const operation = intent || { kind, body }; if (intent && kind !== intent.kind) return;
    pending.current = true; setBusy(true); setMessage("");
    try {
      sessionStorage.setItem(storage, JSON.stringify(operation)); setIntent(operation);
      const scope = `${owner}:${reservationId}:${operation.kind}`, key = await bookingRequestKey(scope, operation.body);
      await axios.post(`${BACKEND_URL}/api/scheduling/reservations/${reservationId}/${operation.kind}`, operation.body, { withCredentials: true, headers: { "Idempotency-Key": key } });
      if (!alive.current || currentScope.current !== storage) return;
      clearBookingRequest(scope); clearIntent(); setDialog(null); setMessage("Your visit change is confirmed."); resource.refresh();
    } catch (error) {
      if (!alive.current || currentScope.current !== storage) return;
      setMessage(error.response?.data?.message || "Response interrupted. Retry the last change with its original request.");
      if (error.response && error.response.status < 500) { clearIntent(); if (error.response.status === 409) availability.refresh(); }
      resource.refresh();
    } finally { if (currentScope.current === storage) { pending.current = false; if (alive.current) setBusy(false); } }
  };
  const download = () => { try { downloadText("medipulse-visit.ics", calendarReminder(visit), "text/calendar"); } catch { setMessage("A confirmed visit is required for a calendar reminder."); } };
  if (loader) return <main className="mp-page"><LoadingState>Checking your patient session...</LoadingState></main>;
  if (!owner) return <main className="mp-page"><EmptyState title="Sign in to follow your visit" action={<Button to={"/login?returnTo=" + encodeURIComponent(location.pathname)}>Patient sign in</Button>}>Your reservation and care information are available to the booking account.</EmptyState></main>;
  if (!visit) return <main className="mp-page"><h1>Your reservation</h1>{resource.error ? <Banner action={<Button onClick={resource.refresh}>Retry</Button>}>{resource.error}</Banner> : <LoadingState>Loading your reservation...</LoadingState>}</main>;
  if (product.kind === "patient" && (!hospital?._id || visit.session.hospitalId !== hospital._id)) return <main className="mp-page">{!hospital?._id ? <LoadingState>Checking the hospital context...</LoadingState> : <EmptyState title="This reservation belongs to another care context." />}</main>;
  const { reservation, session, appointment, token } = visit;
  const terminal = ["cancelled", "completed", "expired"].includes(reservation.state);
  return <main className="mp-page mp-page--patient"><div className="mp-section-heading"><div><p className="mp-eyebrow">Your next step in care</p><h1>{reservation.state === "confirmed" ? "Your visit is confirmed" : "Your reservation"}</h1><p>{careLabels[session.appointmentType]} · {session.timezone}</p></div><StatusBadge status={terminal ? reservation.state : appointment?.admissionState === "reserved" ? "reserved" : appointment?.status || reservation.state} /></div>
    {!online && <Banner>You are offline. Displayed details are from your last successful refresh.</Banner>}{resource.error && <Banner action={<Button onClick={resource.refresh} variant="secondary">Retry refresh</Button>}>{resource.error} Displayed details may be out of date.</Banner>}{message && <Banner tone={message.includes("confirmed") ? "info" : "error"}>{message}</Banner>}{intent && <Banner tone="info" action={<Button disabled={busy || !online} onClick={() => change(intent.kind, intent.body)}>Retry last change</Button>}>A visit change needs confirmation. Its original details and request key are retained.</Banner>}
    <div className="mp-booking-layout"><div className="mp-stack"><Card><div className="mp-card-heading"><h2>{token?.displayToken ? "Token " + token.displayToken : "Visit details"}</h2><Check size={21} aria-hidden="true" /></div><dl className="mp-details"><div><dt>Patient</dt><dd>{reservation.familyMemberId ? "Selected family member" : "Myself"}</dd></div><div><dt>{session.appointmentType === "online_opd" ? "OPD window starts" : "Appointment starts"}</dt><dd>{visitTime(reservation.startsAt, session.timezone)}</dd></div><div><dt>Ends</dt><dd>{visitTime(reservation.endsAt, session.timezone)}</dd></div><div><dt>Visit mode</dt><dd>{session.visitMode === "in_person" ? "In person at the hospital" : "Online · microphone required"}</dd></div><div><dt>Arrival</dt><dd>{appointment?.admissionState === "arrived" ? "Check-in recorded" : "Not checked in"}</dd></div><div><dt>Queue position</dt><dd>{visit.queuePosition != null ? visit.queuePosition === 0 ? "In consultation" : "#" + visit.queuePosition : "Not available before queue admission"}</dd></div><div><dt>Estimated wait</dt><dd>{visit.estimatedWaitMinutes != null ? visit.estimatedWaitMinutes + " minutes" : "Not available"}</dd></div>{session.visitMode === "in_person" && <div><dt>Room / destination</dt><dd>{visit.location?.room || "Not recorded — ask reception for directions"}</dd></div>}</dl></Card>
      <Card><h2>What happens next</h2>{reservation.state === "held" && <Button to={(product.kind === "patient" ? "/?doctor=" + session.doctorId + "&" : "/appointment/book/" + session.doctorId + "?") + new URLSearchParams({ reservation: reservation._id, type: session.appointmentType, date: session.serviceDate, slot: reservation.slotId })}>Review held slot</Button>}<p className="mp-visit-note">{visit.nextStep}</p>{session.appointmentType === "online_opd" && <p>The OPD window is a queue session. The consultation time depends on the live queue.</p>}{!terminal && appointment?.admissionState === "reserved" && <p className="mp-field-hint">Arrival opens {session.policy.checkInLeadMinutes} minutes before the start. {session.visitMode === "in_person" ? "Hospital staff confirm your physical arrival." : "Check in online when the button becomes available."}</p>}{canCheckIn(visit, clock) && <Button disabled={busy || !online || Boolean(intent)} onClick={() => change("check-in")}>Check in online <ArrowRight size={16} aria-hidden="true" /></Button>}{session.visitMode === "in_person" && !terminal && <Button to="/visits" variant="secondary">Hospital visit tracking</Button>}</Card>
      {appointment?.status === "active" && session.visitMode === "online" && <CallPanel key={appointment._id} appointmentId={appointment._id} onRefresh={resource.refresh} />}
      <Card><h2><HelpCircle size={19} aria-hidden="true" /> Need help?</h2><p>{session.visitMode === "in_person" ? "Show this reservation at hospital reception. Staff can confirm arrival and direct you to the next destination." : "Refresh this page if the doctor has called you. You can leave and rejoin an active online consultation."}</p></Card></div>
      <aside className="mp-stack"><Card><h2>Fee and payment</h2><div className="mp-fee-row"><span>Consultation</span><strong>{feeText(reservation.fee)}</strong></div><div className="mp-fee-row"><span>Total demo credits</span><strong>{feeText(reservation.fee)}</strong></div><p>{appointment?.payment?.refundState === "completed" ? "Demo-credit refund completed" : appointment?.payment?.paid ? "Demo-credit payment confirmed" : "No payment confirmed"}</p><p className="mp-field-hint">No real money is collected.</p></Card><Card><h2>Manage this visit</h2><p className="mp-field-hint">Cancel before the start minus {session.policy.cancelBeforeMinutes} minutes. Reschedule before the start minus {session.policy.rescheduleBeforeMinutes} minutes. Provider unavailability allows eligible changes after the cutoff.</p><div className="mp-stack">{visit.rescheduling?.allowed && <Button variant="secondary" disabled={busy || !online || Boolean(intent)} onClick={() => { setDate(session.serviceDate); setTarget(""); setDialog("reschedule"); }}>Reschedule visit</Button>}{visit.cancellation?.allowed && <Button variant="danger" disabled={busy || !online || Boolean(intent)} onClick={() => setDialog("cancel")}>Cancel reservation</Button>}{reservation.state === "confirmed" && <Button variant="secondary" onClick={download}><CalendarPlus size={17} />Download calendar reminder</Button>}<Button variant="ghost" disabled={!online} onClick={resource.refresh}><RefreshCcw size={16} />Refresh visit</Button><Button to={product.kind === "patient" ? "/visits" : "/my-appointments"} variant="ghost">All my visits</Button></div><p className="mp-field-hint">Import the calendar file into your calendar to receive its reminders.</p></Card><p className="mp-field-hint"><Clock3 size={14} aria-hidden="true" />Last refreshed {resource.refreshedAt?.toLocaleTimeString() || "Not available"}. Live status refreshes every 10 seconds.</p></aside></div>
    <Dialog open={Boolean(dialog)} onClose={() => { if (!busy) { setDialog(null); setParams(params => { params.delete("manage"); return params; }, { replace: true }); } }} title={dialog === "cancel" ? "Cancel this reservation?" : "Reschedule your visit"}>{message && !message.includes("confirmed") && <Banner>{message}</Banner>}{intent && <Banner tone="info" action={<Button disabled={busy || !online} onClick={() => change(intent.kind, intent.body)}>Retry last change</Button>}>The previous change needs confirmation.</Banner>}{dialog === "cancel" ? <div className="mp-stack"><p>Cancel this visit and return its {feeText(reservation.fee)} demo-credit payment. Care already started cannot be cancelled.</p><Button disabled={busy || !online} variant="danger" onClick={() => change("cancel")}>{busy ? "Cancelling..." : "Confirm cancellation"}</Button></div> : <div className="mp-stack"><p>Choose real availability for the same doctor, practice, care type and fee. Your current visit stays reserved until the move succeeds.</p><Field data-autofocus label="New service date" type="date" min={dateInZone(new Date(), session.timezone)} value={date} onChange={event => { setDate(event.target.value); setTarget(""); }} />{availability.error && <Banner action={<Button onClick={availability.refresh}>Retry availability</Button>}>{availability.error}</Banner>}{availability.loading && !availability.data ? <LoadingState>Loading available replacements...</LoadingState> : !slots.length ? <EmptyState title="No matching availability on this date." /> : <fieldset className="mp-choice-group"><legend>Replacement slot</legend><div className="mp-slot-grid">{slots.map(slot => <label key={slot._id} className={"mp-slot " + (slot._id === target ? "mp-slot--selected" : "")}><input type="radio" name="replacement-slot" disabled={!slot.bookable || slot._id === reservation.slotId || busy || Boolean(intent)} checked={target === slot._id} onChange={() => setTarget(slot._id)} /><strong>{timeOfDay(slot.startsAt, session.timezone)} – {timeOfDay(slot.endsAt, session.timezone)}</strong><small>{slot.bookable ? slot.remaining + " available" : "Unavailable"}</small></label>)}</div></fieldset>}<Button disabled={busy || !online || !slots.some(slot => slot._id === target && slot.bookable) || Boolean(availability.error) || availability.loading || Boolean(intent)} onClick={() => change("reschedule", { slotId: target, revision: reservation.revision })}>{busy ? "Moving reservation..." : "Confirm new slot"}</Button></div>}</Dialog>
  </main>;
}
