import test from "node:test";
import assert from "node:assert/strict";
import { invitationDoctorProfile, profileDraft, profilePayload, signupPayload, phoneValid, staffDestination } from "../src/utils/accountForms.js";
const doctor = { firstName: "Fixture", lastName: "Doctor", gender: "other", experience: { years: 0, expertise: "General Medicine", qualification: "Recorded qualification" }, clinic: { name: "Fixture Clinic", location: "Fixture", pin: 123456, phoneNumber: 9876543210 }, consultationFee: 0 };
test("profile drafts retain recorded zero values", () => { const draft = profileDraft(doctor); assert.equal(draft.years, "0"); assert.equal(draft.consultationFee, "0"); });
test("doctor updates preserve unedited nested professional and clinic information", () => { const payload = profilePayload({ ...profileDraft(doctor), bio: "Updated", consultationFee: "125.55" }, doctor, "doctor"); assert.equal(payload.experience.qualification, doctor.experience.qualification); assert.equal(payload.clinic.pin, doctor.clinic.pin); assert.equal(payload.clinic.phoneNumber, doctor.clinic.phoneNumber); assert.equal(payload.consultationFee, 125.55); });
test("blank optional recorded values are not invented as zero", () => { const payload = profilePayload({ ...profileDraft(doctor), years: "", consultationFee: "", phoneNumber: "" }, doctor, "doctor"); assert.equal(payload.experience.years, 0); assert.equal(Object.hasOwn(payload, "consultationFee"), false); assert.equal(Object.hasOwn(payload, "phone"), false); });
test("patient profile payload excludes clinical and staff mutations", () => { const payload = profilePayload(profileDraft(doctor), doctor, "user"); assert.deepEqual(Object.keys(payload).sort(), ["bio", "firstName", "gender", "lastName"]); });
test("invalid specialty, experience, fee and phone are rejected", () => { for (const values of [{ expertise: " " }, { years: "-1" }, { years: "1.5" }, { consultationFee: "-1" }, { consultationFee: "bad" }, { phoneNumber: "123" }]) assert.throws(() => profilePayload({ ...profileDraft(doctor), ...values }, doctor, "doctor")); });
test("signup omits empty optional fields while retaining explicit zero experience", () => { assert.deepEqual(signupPayload({ firstName: "Fixture", years: "0", phone: "", confirmPassword: "private" }), { firstName: "Fixture", years: "0" }); });
test("phone validation matches existing 10-digit contracts", () => { assert.equal(phoneValid(""), true); assert.equal(phoneValid("9876543210"), true); assert.equal(phoneValid("0123456789"), false); assert.equal(phoneValid("short"), false); });
test("staff roles open their operational workspace", () => { for(const role of ["NURSE", "RECEPTIONIST"]) assert.equal(staffDestination({ role }), "/hospital/nursing-station"); assert.equal(staffDestination({ role: "DOCTOR" }), "/hospital/doctor-opd"); assert.equal(staffDestination({ role: "HOSPITAL_ADMIN" }), "/hospital/admin"); assert.equal(staffDestination({ role: "LAB_TECH" }), "/hospital/staff-communication"); });

test("invitation experience preserves explicit zero through the existing fallback", () => { const body = invitationDoctorProfile({ specialization: "General Medicine", qualification: "Recorded", experience: "0" }); assert.equal(Number(body.experience || 5), 0); assert.equal(Object.hasOwn(invitationDoctorProfile({ experience: "" }), "experience"), false); });
